### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by bokers** [aruis/mysql_vs_postgresql#2]
MySQL 肯定会比PG弱，这是毫无疑问的，但是应该没你呈现得那么离谱....

不妨把 MySQL 和 PG 的优化都拉满，再来看看差距会不会还是那么巨大。

**Comment by aruis** [comment]
是的，所以我这个只能算是非客观对比。。。 但是mysql的优化我确实不会。 pg的优化，我在项目中陆续经历了几次，最后发现默认的配置有时候比自己优化的还靠谱，所以没再深究了。
